name: yuenhom
favicon: null
layout_spectrum: 0.83217983529903
typography_spectrum: 0.22349635371938348
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.1649937448091805
  lightness: 0.9846391824539751
  saturation: 0.270376096945256
  rhythmicContrast: 0.7543896515853703
purpose: []
